import { League, MatchResolveType, PeriodType, Provider, ScoringType, Sport } from '../enums/sports';

export const LeagueMap = {
    [League.NCAAF]: {
        sport: Sport.FOOTBALL,
        id: League.NCAAF,
        label: 'NCAA Football',
        opticOddsName: 'NCAAF',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.NFL]: {
        sport: Sport.FOOTBALL,
        id: League.NFL,
        label: 'NFL',
        opticOddsName: 'NFL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.MLB]: {
        sport: Sport.BASEBALL,
        id: League.MLB,
        label: 'MLB',
        opticOddsName: 'MLB',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.INNING,
        isDrawAvailable: false,
    },
    [League.NBA]: {
        sport: Sport.BASKETBALL,
        id: League.NBA,
        label: 'NBA',
        opticOddsName: 'NBA',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.NCAAB]: {
        sport: Sport.BASKETBALL,
        id: League.NCAAB,
        label: 'NCAA Basketball',
        opticOddsName: 'NCAAB',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.NHL]: {
        sport: Sport.HOCKEY,
        id: League.NHL,
        label: 'NHL',
        opticOddsName: 'NHL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: false,
    },
    [League.UFC]: {
        sport: Sport.FIGHTING,
        id: League.UFC,
        label: 'UFC',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.ROUNDS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.ROUND,
        isDrawAvailable: false,
    },
    [League.WNBA]: {
        sport: Sport.BASKETBALL,
        id: League.WNBA,
        label: 'WNBA',
        opticOddsName: 'WNBA',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.MLS]: {
        sport: Sport.SOCCER,
        id: League.MLS,
        label: 'MLS',
        opticOddsName: 'USA - Major League Soccer',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.EPL]: {
        sport: Sport.SOCCER,
        id: League.EPL,
        label: 'EPL',
        opticOddsName: 'England - Premier League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.LIGUE_ONE]: {
        sport: Sport.SOCCER,
        id: League.LIGUE_ONE,
        label: 'Ligue 1',
        opticOddsName: 'France - Ligue 1',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.BUNDESLIGA]: {
        sport: Sport.SOCCER,
        id: League.BUNDESLIGA,
        label: 'Bundesliga',
        opticOddsName: 'Germany - Bundesliga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.LA_LIGA]: {
        sport: Sport.SOCCER,
        id: League.LA_LIGA,
        label: 'La Liga',
        opticOddsName: 'Spain - La Liga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SERIE_A]: {
        sport: Sport.SOCCER,
        id: League.SERIE_A,
        label: 'Serie A',
        opticOddsName: 'Italy - Serie A',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },

    [League.UEFA_CL]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CL,
        label: 'UEFA Champions League',
        opticOddsName: 'UEFA - Champions League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_EL]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EL,
        label: 'UEFA Europa League',
        opticOddsName: 'UEFA - Europa League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FIFA_WC]: {
        sport: Sport.SOCCER,
        id: League.FIFA_WC,
        label: 'FIFA World Cup Qualifiers',
        provider: Provider.OPTICODDS,
        opticOddsName: 'FIFA - World Cup Qualifiers',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.J1_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.J1_LEAGUE,
        label: 'J1 League',
        opticOddsName: 'Japan - J1 League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.IPL]: {
        sport: Sport.CRICKET,
        id: League.IPL,
        label: 'Indian Premier League',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.INNING,
        isDrawAvailable: false,
    },
    [League.T20_BLAST]: {
        sport: Sport.CRICKET,
        id: League.T20_BLAST,
        label: 'T20 Blast',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.INNING,
        isDrawAvailable: false,
    },
    [League.IIHF_WORLD_CHAMPIONSHIP]: {
        sport: Sport.HOCKEY,
        id: League.IIHF_WORLD_CHAMPIONSHIP,
        label: 'IIHF World Championship',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.COPA_AMERICA]: {
        sport: Sport.SOCCER,
        id: League.COPA_AMERICA,
        label: 'Copa America',
        opticOddsName: 'CONMEBOL - Copa America',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.COPA_LIBERTADORES]: {
        sport: Sport.SOCCER,
        id: League.COPA_LIBERTADORES,
        label: 'Copa Libertadores',
        opticOddsName: 'CONMEBOL - Copa Libertadores',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_EURO]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EURO,
        label: 'UEFA EURO 2024',
        opticOddsName: 'UEFA - European Championship',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.EREDIVISIE]: {
        sport: Sport.SOCCER,
        id: League.EREDIVISIE,
        label: 'Eredivisie',
        opticOddsName: 'Netherlands - Eredivisie',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.PRIMEIRA_LIGA]: {
        sport: Sport.SOCCER,
        id: League.PRIMEIRA_LIGA,
        label: 'Primeira Liga',
        opticOddsName: 'Portugal - Primeira Liga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_SOCCER_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.SUMMER_OLYMPICS_SOCCER_WOMEN,
        label: 'Olympic Games Soccer Women',
        opticOddsName: 'Olympics Soccer Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_SOCCER]: {
        sport: Sport.SOCCER,
        id: League.SUMMER_OLYMPICS_SOCCER,
        label: 'Olympic Games Soccer',
        opticOddsName: 'Olympics Soccer Men',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FIFA_WC_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.FIFA_WC_WOMEN,
        label: 'FIFA World Cup Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ENGLAND_FA_CUP]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_FA_CUP,
        label: 'FA Cup',
        opticOddsName: 'England - FA Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FRANCE_CUP]: {
        sport: Sport.SOCCER,
        id: League.FRANCE_CUP,
        label: 'Coupe de France',
        opticOddsName: 'France - Coupe de France',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SPAIN_CUP]: {
        sport: Sport.SOCCER,
        id: League.SPAIN_CUP,
        label: 'Copa del Rey',
        opticOddsName: 'Spain - Copa del Rey',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ITALY_CUP]: {
        sport: Sport.SOCCER,
        id: League.ITALY_CUP,
        label: 'Coppa Italia',
        opticOddsName: 'Italy - Coppa Italia',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.TENNIS_WTA]: {
        sport: Sport.TENNIS,
        id: League.TENNIS_WTA,
        label: 'WTA Events',
        opticOddsName: 'WTA',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.TENNIS_GS]: {
        sport: Sport.TENNIS,
        id: League.TENNIS_GS,
        label: 'Grand Slam',
        opticOddsName: 'ATP,WTA',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.TENNIS_MASTERS]: {
        sport: Sport.TENNIS,
        id: League.TENNIS_MASTERS,
        label: 'ATP Events',
        opticOddsName: 'ATP',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_TENNIS]: {
        sport: Sport.TENNIS,
        id: League.SUMMER_OLYMPICS_TENNIS,
        label: 'Olympic Games Tennis',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.GERMANY_CUP]: {
        sport: Sport.SOCCER,
        id: League.GERMANY_CUP,
        label: 'DFB Pokal',
        opticOddsName: 'Germany - DFB Pokal',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.LIGA_MX]: {
        sport: Sport.SOCCER,
        id: League.LIGA_MX,
        label: 'Liga MX',
        opticOddsName: 'Mexico - Liga MX',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.BRAZIL_1]: {
        sport: Sport.SOCCER,
        id: League.BRAZIL_1,
        label: 'Serie A',
        opticOddsName: 'Brazil - Serie A',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_EURO_U21]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EURO_U21,
        label: 'UEFA EURO U21',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FIFA_WORLD_CUP_U20]: {
        sport: Sport.SOCCER,
        id: League.FIFA_WORLD_CUP_U20,
        label: 'FIFA World Cup U20',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CZECH_REPUBLIC_EXTRALIGA]: {
        sport: Sport.HOCKEY,
        id: League.CZECH_REPUBLIC_EXTRALIGA,
        label: 'Czech Republic Extraliga',
        opticOddsName: 'Czech Republic - Extraliga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.FINLAND_SM_LIIGA]: {
        sport: Sport.HOCKEY,
        id: League.FINLAND_SM_LIIGA,
        label: 'Finland SM Liiga',
        opticOddsName: 'Finland - SM Liiga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.RUSSIA_KHL]: {
        sport: Sport.HOCKEY,
        id: League.RUSSIA_KHL,
        label: 'Russia KHL',
        opticOddsName: 'Russia - KHL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.GERMANY_DEL]: {
        sport: Sport.HOCKEY,
        id: League.GERMANY_DEL,
        label: 'Germany DEL',
        opticOddsName: 'Germany - DEL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.AUSTRIA_ICE_HOCKEY_LEAGUE]: {
        sport: Sport.HOCKEY,
        id: League.AUSTRIA_ICE_HOCKEY_LEAGUE,
        label: 'Austria Ice Hockey League',
        opticOddsName: 'Austria - Ice Hockey League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.SWEDEN_SHL]: {
        sport: Sport.HOCKEY,
        id: League.SWEDEN_SHL,
        label: 'Sweden SHL',
        opticOddsName: 'Sweden - SHL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.SWITZETLAND_NATIONAL_LEAGUE]: {
        sport: Sport.HOCKEY,
        id: League.SWITZETLAND_NATIONAL_LEAGUE,
        label: 'Switzerland National League',
        opticOddsName: 'Switzerland - National League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_HANDBALL_WOMEN]: {
        sport: Sport.HANDBALL,
        id: League.SUMMER_OLYMPICS_HANDBALL_WOMEN,
        label: 'Olympic Games Handball Women',
        opticOddsName: 'Olympics Handball Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_HANDBALL]: {
        sport: Sport.HANDBALL,
        id: League.SUMMER_OLYMPICS_HANDBALL,
        label: 'Olympic Games Handball',
        opticOddsName: 'Olympics Handball Men',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.EUROLEAGUE]: {
        sport: Sport.BASKETBALL,
        id: League.EUROLEAGUE,
        label: 'Euroleague',
        opticOddsName: 'Euroleague',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL,
        label: 'Olympic Games Basketball',
        opticOddsName: 'Olympics Basketball Men',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL_WOMEN]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
        label: 'Olympic Games Basketball Women',
        opticOddsName: 'Olympics Basketball Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FIBA_WORLD_CUP]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_WORLD_CUP,
        label: 'FIBA World Cup',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FORMULA1]: {
        sport: Sport.MOTOSPORT,
        id: League.FORMULA1,
        label: 'Formula 1',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
        label: 'Olympic Games Beach Voleyball Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_BEACH_VOLEYBALL]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
        label: 'Olympic Games Beach Voleyball',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_TABLE_TENNIS]: {
        sport: Sport.TABLE_TENNIS,
        id: League.SUMMER_OLYMPICS_TABLE_TENNIS,
        label: 'Olympic Games Table Tennis',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.MOTOGP]: {
        sport: Sport.MOTOSPORT,
        id: League.MOTOGP,
        label: 'MotoGP',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.SAUDI_PROFESSIONAL_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SAUDI_PROFESSIONAL_LEAGUE,
        label: 'Saudi Professional League',
        opticOddsName: 'Saudi Arabia - Saudi League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_WATERPOLO]: {
        sport: Sport.WATERPOLO,
        id: League.SUMMER_OLYMPICS_WATERPOLO,
        label: 'Olympic Games Water Polo',
        opticOddsName: 'Olympics Water Polo',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_VOLEYBALL_WOMEN]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
        label: 'Olympic Games Volleyball Women',
        opticOddsName: 'Olympics Volleyball Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_VOLEYBALL]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_VOLEYBALL,
        label: 'Olympic Games Volleyball',
        opticOddsName: 'Olympics Volleyball Men',
        provider: Provider.EMPTY,
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
    },
    [League.BOXING]: {
        sport: Sport.FIGHTING,
        id: League.BOXING,
        label: 'Boxing',
        provider: Provider.EMPTY,
        scoringType: ScoringType.ROUNDS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.ROUND,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_RUGBY]: {
        sport: Sport.RUGBY,
        id: League.SUMMER_OLYMPICS_RUGBY,
        label: 'Olympic Games Rugby',
        opticOddsName: 'Olympics Rugby 7s Men',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_RUGBY_WOMEN]: {
        sport: Sport.RUGBY,
        id: League.SUMMER_OLYMPICS_RUGBY_WOMEN,
        label: 'Olympic Games Rugby Women',
        opticOddsName: 'Olympics Rugby 7s Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_HOCKEY_WOMEN]: {
        sport: Sport.HOCKEY,
        id: League.SUMMER_OLYMPICS_HOCKEY_WOMEN,
        label: 'Olympic Games Hockey Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.SUMMER_OLYMPICS_HOCKEY]: {
        sport: Sport.HOCKEY,
        id: League.SUMMER_OLYMPICS_HOCKEY,
        label: 'Olympic Games Hockey',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
    },
    [League.UEFA_NATIONS_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.UEFA_NATIONS_LEAGUE,
        label: 'UEFA Nations League',
        provider: Provider.OPTICODDS,
        opticOddsName: 'UEFA - Nations League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CONCACAF_NATIONS_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.CONCACAF_NATIONS_LEAGUE,
        label: 'CONCACAF Nations League',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CSGO]: {
        sport: Sport.ESPORTS,
        id: League.CSGO,
        label: 'CS GO',
        opticOddsName: 'CS2',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.DOTA2]: {
        sport: Sport.ESPORTS,
        id: League.DOTA2,
        label: 'DOTA 2',
        opticOddsName: 'Dota 2',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL_3X3]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL_3X3,
        label: 'Olympic Games Basketball 3x3',
        opticOddsName: 'Olympics Basketball 3x3 Men',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
        label: 'Olympic Games Basketball 3x3 Women',
        opticOddsName: 'Olympics Basketball 3x3 Women',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.SUMMER_OLYMPICS_QUALIFICATION]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_QUALIFICATION,
        label: 'Summer Olympics Basketball Qualification',
        provider: Provider.EMPTY,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.LOL]: {
        sport: Sport.ESPORTS,
        id: League.LOL,
        label: 'LOL',
        opticOddsName: 'League of Legends',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.CONMEBOL_WC_QUALIFICATIONS]: {
        sport: Sport.SOCCER,
        id: League.CONMEBOL_WC_QUALIFICATIONS,
        label: 'CONMEBOL WC Qualification',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_CONFERENCE_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CONFERENCE_LEAGUE,
        label: 'UEFA Conference League',
        opticOddsName: 'UEFA - Europa Conference League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.NON_TITLE_BOXING]: {
        sport: Sport.FIGHTING,
        id: League.NON_TITLE_BOXING,
        label: 'Boxing',
        provider: Provider.EMPTY,
        scoringType: ScoringType.ROUNDS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.ROUND,
        isDrawAvailable: false,
    },
    [League.UEFA_CHAMPIONS_LEAGUE_QUALIFICATION]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CHAMPIONS_LEAGUE_QUALIFICATION,
        label: 'UEFA Champions League Qualification',
        opticOddsName: 'UEFA - Champions League',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_EUROPA_LEAGUE_QUALIFICATION]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EUROPA_LEAGUE_QUALIFICATION,
        label: 'UEFA Europa League Qualification',
        opticOddsName: 'UEFA - Europa League',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_CONFERENCE_LEAGUE_QUALIFICATION]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CONFERENCE_LEAGUE_QUALIFICATION,
        label: 'UEFA Conference League Qualification',
        opticOddsName: 'UEFA - Europa Conference League',
        provider: Provider.EMPTY,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.US_ELECTION]: {
        sport: Sport.POLITICS,
        id: League.US_ELECTION,
        label: 'US Election 2024',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.UEFA_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.UEFA_SUPER_CUP,
        label: 'UEFA Super Cup',
        opticOddsName: 'UEFA - Super Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.BRAZIL_CUP]: {
        sport: Sport.SOCCER,
        id: League.BRAZIL_CUP,
        label: 'Copa do Brasil',
        opticOddsName: 'Brazil - Copa do Brasil',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ENGLAND_CHAMPIONSHIP]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_CHAMPIONSHIP,
        label: 'EFL Championship',
        opticOddsName: 'England - Championship',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SCOTLAND_PREMIERSHIP]: {
        sport: Sport.SOCCER,
        id: League.SCOTLAND_PREMIERSHIP,
        label: 'Scotland Premiership',
        opticOddsName: 'Scotland - Premiership',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.BELGIUM_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.BELGIUM_LEAGUE,
        label: 'Belgium Jupiler Pro League',
        opticOddsName: 'Belgium - Jupiler Pro League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CZECH_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.CZECH_LEAGUE,
        label: 'Czech Republic FNL',
        opticOddsName: 'Czech Republic - FNL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CHILE_PRIMERA]: {
        sport: Sport.SOCCER,
        id: League.CHILE_PRIMERA,
        label: 'Chile Primera Division',
        opticOddsName: 'Chile - Primera Division',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FINLAND_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.FINLAND_LEAGUE,
        label: 'Finland Veikkausliiga',
        opticOddsName: 'Finland - Veikkausliiga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ARGENTINA_PRIMERA]: {
        sport: Sport.SOCCER,
        id: League.ARGENTINA_PRIMERA,
        label: 'Argentina Primera Division',
        opticOddsName: 'Argentina - Primera Division',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.RUSSIA_PREMIER]: {
        sport: Sport.SOCCER,
        id: League.RUSSIA_PREMIER,
        label: 'Russia Premier League',
        opticOddsName: 'Russia - Premier League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.TURKEY_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.TURKEY_SUPER_LEAGUE,
        label: 'Turkey Super Lig',
        opticOddsName: 'Turkey - Super Lig',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SERBIA_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SERBIA_SUPER_LEAGUE,
        label: 'Serbia Super Liga',
        opticOddsName: 'Serbia - Super Liga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.GREECE_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.GREECE_SUPER_LEAGUE,
        label: 'Greece Super League',
        opticOddsName: 'Greece - Super League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.INDIA_PREMIER]: {
        sport: Sport.SOCCER,
        id: League.INDIA_PREMIER,
        label: 'India Calcutta Premier Division',
        opticOddsName: 'India - Calcutta Premier Division',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CHINA_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.CHINA_SUPER_LEAGUE,
        label: 'China Super League',
        opticOddsName: 'China - Super League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.AUSTRALIA_A_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.AUSTRALIA_A_LEAGUE,
        label: 'Australia A-League',
        opticOddsName: 'Australia - A-League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SWITZERLAND_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SWITZERLAND_SUPER_LEAGUE,
        label: 'Switzerland Super League',
        opticOddsName: 'Switzerland - Super League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.BUNDESLIGA_2]: {
        sport: Sport.SOCCER,
        id: League.BUNDESLIGA_2,
        label: 'Bundesliga 2',
        opticOddsName: 'Germany - Bundesliga 2',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.LA_LIGA_2]: {
        sport: Sport.SOCCER,
        id: League.LA_LIGA_2,
        label: 'La Liga 2',
        opticOddsName: 'Spain - La Liga 2',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SERIE_B]: {
        sport: Sport.SOCCER,
        id: League.SERIE_B,
        label: 'Serie B',
        opticOddsName: 'Italy - Serie B',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.INDIA_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.INDIA_SUPER_LEAGUE,
        label: 'India Super League',
        opticOddsName: 'India - Super League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.LIGUE_2]: {
        sport: Sport.SOCCER,
        id: League.LIGUE_2,
        label: 'Ligue 2',
        opticOddsName: 'France - Ligue 2',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.AUSTRIA_BUNDESLIGA]: {
        sport: Sport.SOCCER,
        id: League.AUSTRIA_BUNDESLIGA,
        label: 'Austria Bundesliga',
        opticOddsName: 'Austria - Bundesliga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.DENMARK_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.DENMARK_SUPER_LEAGUE,
        label: 'Denmark Superliga',
        opticOddsName: 'Denmark - Superliga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.POLAND_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.POLAND_LEAGUE,
        label: 'Poland Ekstraklasa',
        opticOddsName: 'Poland - Ekstraklasa',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SWEDEN_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SWEDEN_LEAGUE,
        label: 'Sweden Allsvenskan',
        opticOddsName: 'Sweden - Allsvenskan',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.COLOMBIA_PRIMERA_A]: {
        sport: Sport.SOCCER,
        id: League.COLOMBIA_PRIMERA_A,
        label: 'Colombia Primera A',
        opticOddsName: 'Colombia - Primera A',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ENGLAND_EFL_CUP]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_EFL_CUP,
        label: 'England EFL Cup',
        opticOddsName: 'England - EFL Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ENGLAND_LEGAUE_1]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_LEGAUE_1,
        label: 'England League 1',
        opticOddsName: 'England - League 1',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.URUGUAY_PRIMERA_DIVISION]: {
        sport: Sport.SOCCER,
        id: League.URUGUAY_PRIMERA_DIVISION,
        label: 'Uruguay Primera Division',
        opticOddsName: 'Uruguay - Primera Division',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.AFC_CHAMPIONS_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.AFC_CHAMPIONS_LEAGUE,
        label: 'AFC Champions League',
        opticOddsName: 'AFC - Champions League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ITALY_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.ITALY_SUPER_CUP,
        label: 'Italy Super Cup',
        opticOddsName: 'Italy - Supercoppa',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FRANCE_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.FRANCE_SUPER_CUP,
        label: 'France Super Cup',
        opticOddsName: 'France - Super Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SPAIN_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.SPAIN_SUPER_CUP,
        label: 'Spain Super Cup',
        opticOddsName: 'Spain - Supercopa',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.GERMANY_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.GERMANY_SUPER_CUP,
        label: 'Germany Super Cup',
        opticOddsName: 'Germany - Super Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.PORTUGAL_LEAGUE_CUP]: {
        sport: Sport.SOCCER,
        id: League.PORTUGAL_LEAGUE_CUP,
        label: 'Portugal League Cup',
        opticOddsName: 'Portugal - League Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.THAILAND_LEAGUE_1]: {
        sport: Sport.SOCCER,
        id: League.THAILAND_LEAGUE_1,
        label: 'Thai League 1',
        opticOddsName: 'Thailand - Thai League 1',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.NETHERLANDS_CUP]: {
        sport: Sport.SOCCER,
        id: League.NETHERLANDS_CUP,
        label: 'Netherlands KNVB Beker',
        opticOddsName: 'Netherlands - KNVB Beker',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.PORTUGAL_CUP]: {
        sport: Sport.SOCCER,
        id: League.PORTUGAL_CUP,
        label: 'Taca de Portugal',
        opticOddsName: 'Portugal - Taca de Portugal',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },

    [League.ENGLAND_SUPER_LEAGUE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_SUPER_LEAGUE_WOMEN,
        label: "England Women's Super League",
        opticOddsName: 'England - Womens Super League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.ITALY_SERIE_A_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.ITALY_SERIE_A_WOMEN,
        label: 'Italy Serie A Femminile',
        opticOddsName: 'Italy - Serie A Femminile',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.FRANCE_PREMIERE_LIGUE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.FRANCE_PREMIERE_LIGUE_WOMEN,
        label: 'France Premiere Ligue Women',
        opticOddsName: 'France - Premiere Ligue',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.GERMANY_BUNDESLIGA_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.GERMANY_BUNDESLIGA_WOMEN,
        label: 'Germany Frauen Bundesliga',
        opticOddsName: 'Germany - Frauen Bundesliga',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.SPAIN_LIGA_F_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.SPAIN_LIGA_F_WOMEN,
        label: 'Spain Liga F Women',
        opticOddsName: 'Spain - Liga F',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.NETHERLANDS_EREDIVISIE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.NETHERLANDS_EREDIVISIE_WOMEN,
        label: 'Netherlands Eredivisie Women',
        opticOddsName: 'Netherlands - Vrouwen Eredivisie',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.BELGIUM_SUPER_LEAGUE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.BELGIUM_SUPER_LEAGUE_WOMEN,
        label: "Belgium Women's Super League",
        opticOddsName: 'Belgium - Womens Super League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_CHAMPIONS_LEAGUE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CHAMPIONS_LEAGUE_WOMEN,
        label: 'UEFA Champions League Women',
        opticOddsName: 'UEFA - Champions League Women',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.USA_NWSL]: {
        sport: Sport.SOCCER,
        id: League.USA_NWSL,
        label: 'USA NWSL',
        opticOddsName: 'USA - NWSL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.AUSTRALIA_A_LEAGUE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.AUSTRALIA_A_LEAGUE_WOMEN,
        label: 'Australia A-League Women',
        opticOddsName: 'Australia - A-League Women',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.CONCACAF_CHAMPIONS_CUP]: {
        sport: Sport.SOCCER,
        id: League.CONCACAF_CHAMPIONS_CUP,
        label: 'CONCACAF Champions Cup',
        opticOddsName: 'CONCACAF - Champions Cup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.UEFA_CHAMPIONS_LEAGUE_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CHAMPIONS_LEAGUE_WOMEN,
        label: 'UEFA Nations League Women',
        opticOddsName: 'UEFA - Nations League Women',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
    },
    [League.EUROCUP]: {
        sport: Sport.BASKETBALL,
        id: League.EUROCUP,
        label: 'Eurocup',
        opticOddsName: 'Eurocup',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.SPAIN_LIGA_ACB]: {
        sport: Sport.BASKETBALL,
        id: League.SPAIN_LIGA_ACB,
        label: 'Spain Liga ACB',
        opticOddsName: 'Spain - Liga ACB',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.ITALY_LEGA_BASKET_SERIE_A]: {
        sport: Sport.BASKETBALL,
        id: League.ITALY_LEGA_BASKET_SERIE_A,
        label: 'Italy Lega Basket Serie A',
        opticOddsName: 'Italy - Lega Basket Serie A',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.GERMANY_BBL]: {
        sport: Sport.BASKETBALL,
        id: League.GERMANY_BBL,
        label: 'Germany BBL',
        opticOddsName: 'Germany - BBL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FRANCE_LNB_PRO_A]: {
        sport: Sport.BASKETBALL,
        id: League.FRANCE_LNB_PRO_A,
        label: 'France LNB Pro A',
        opticOddsName: 'France - LNB Pro A',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.CHINA_CBA]: {
        sport: Sport.BASKETBALL,
        id: League.CHINA_CBA,
        label: 'China CBA',
        opticOddsName: 'China - CBA',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.AUSTRALIA_NBL]: {
        sport: Sport.BASKETBALL,
        id: League.AUSTRALIA_NBL,
        label: 'Australia NBL',
        opticOddsName: 'Australia - NBL',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.NCAAW]: {
        sport: Sport.BASKETBALL,
        id: League.NCAAW,
        label: 'NCAAW',
        opticOddsName: 'NCAAW',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FIBA_AMERICUP_QUALIFIERS]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_AMERICUP_QUALIFIERS,
        label: 'FIBA Americup Qualifiers',
        opticOddsName: 'FIBA - Americup Qualifiers',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FIBA_ASIA_CUP_QUALIFIERS]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_ASIA_CUP_QUALIFIERS,
        label: 'FIBA Asia Cup Qualifiers',
        opticOddsName: 'FIBA - Asia Cup Qualifiers',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FIBA_EUROBASKET_QUALIFIERS]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_EUROBASKET_QUALIFIERS,
        label: 'FIBA Eurobasket Qualifiers',
        opticOddsName: 'FIBA - Eurobasket Qualifiers',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FIBA_WORLD_CUP_QUALIFIERS]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_WORLD_CUP_QUALIFIERS,
        label: 'FIBA World Cup Qualifiers',
        opticOddsName: 'FIBA - World Cup Qualifiers',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.FIBA_AFRO_BASKET_QUALIFIERS]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_AFRO_BASKET_QUALIFIERS,
        label: 'FIBA AfroBasket Qualifiers',
        opticOddsName: 'FIBA - AfroBasket Qualifiers',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.GREECE_A1_LEAGUE]: {
        sport: Sport.BASKETBALL,
        id: League.GREECE_A1_LEAGUE,
        label: 'Greece - A1 League',
        opticOddsName: 'Greece - A1 League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
    },
    [League.ROCKET_LEAGUE]: {
        sport: Sport.ESPORTS,
        id: League.ROCKET_LEAGUE,
        label: 'Rocket League',
        opticOddsName: 'Rocket League',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.CALL_OF_DUTY]: {
        sport: Sport.ESPORTS,
        id: League.CALL_OF_DUTY,
        label: 'Call of Duty',
        opticOddsName: 'Call of Duty',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.STARCRAFT]: {
        sport: Sport.ESPORTS,
        id: League.STARCRAFT,
        label: 'Starcraft',
        opticOddsName: 'Starcraft',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.VALORANT]: {
        sport: Sport.ESPORTS,
        id: League.VALORANT,
        label: 'Valorant',
        opticOddsName: 'Valorant',
        provider: Provider.OPTICODDS,
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
    },
    [League.NFL_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NFL_FUTURES,
        label: 'NFL Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.NBA_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NBA_FUTURES,
        label: 'NBA Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.NCAAB_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NCAAB_FUTURES,
        label: 'NCAAB Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.NHL_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NHL_FUTURES,
        label: 'NHL Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.EPL_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.EPL_FUTURES,
        label: 'EPL Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.LIGUE_ONE_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.LIGUE_ONE_FUTURES,
        label: 'Ligue 1 Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.BUNDESLIGA_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.BUNDESLIGA_FUTURES,
        label: 'Bundesliga Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.LA_LIGA_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.LA_LIGA_FUTURES,
        label: 'La Liga',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.SERIE_A_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.SERIE_A_FUTURES,
        label: 'Serie A Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.UEFA_CHAMPIONS_LEAGUE_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.UEFA_CHAMPIONS_LEAGUE_FUTURES,
        label: 'UEFA Champions League Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.ATP_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.ATP_FUTURES,
        label: 'ATP Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.EUROLEAGUE_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.EUROLEAGUE_FUTURES,
        label: 'Euroleague Futures',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.GOLF_H2H]: {
        sport: Sport.GOLF,
        id: League.GOLF_H2H,
        label: 'Golf head-to-head',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
    [League.GOLF_WINNER]: {
        sport: Sport.GOLF,
        id: League.GOLF_WINNER,
        label: 'Golf Tournament Winner',
        provider: Provider.EMPTY,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
    },
};

export const LEAGUES_NO_FORMAL_HOME_AWAY = [
    League.CSGO,
    League.DOTA2,
    League.LOL,
    League.VALORANT,
    League.ROCKET_LEAGUE,
    League.CALL_OF_DUTY,
    League.STARCRAFT,
    League.TENNIS_GS,
    League.TENNIS_MASTERS,
    League.SUMMER_OLYMPICS_TENNIS,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_0,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_1,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_2,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_3,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_4,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_5,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_6,
    League.TENNIS_ATP_GRAND_SLAM_LIVE_MAPPING_V2_7,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_0,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_1,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_2,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_3,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_4,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_5,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_6,
    League.TENNIS_WTA_GRAND_SLAM_LIVE_MAPPING_V2_7,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_1,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_2,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_3,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_4,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_5,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_6,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_7,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_8,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_9,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_10,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_11,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_12,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_13,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_14,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_15,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_16,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_17,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_18,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_19,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_20,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_21,
    League.TENNIS_MASTERS_LIVE_MAPPING_V2_22,
    League.TENNIS_WTA_LIVE_MAPPING_V2_1,
    League.TENNIS_WTA_LIVE_MAPPING_V2_2,
    League.TENNIS_WTA_LIVE_MAPPING_V2_3,
    League.TENNIS_WTA_LIVE_MAPPING_V2_4,
    League.TENNIS_WTA_LIVE_MAPPING_V2_5,
    League.TENNIS_WTA_LIVE_MAPPING_V2_6,
    League.TENNIS_WTA_LIVE_MAPPING_V2_7,
    League.TENNIS_WTA_LIVE_MAPPING_V2_8,
    League.TENNIS_WTA_LIVE_MAPPING_V2_9,
    League.TENNIS_WTA_LIVE_MAPPING_V2_10,
    League.TENNIS_WTA_LIVE_MAPPING_V2_11,
    League.TENNIS_WTA_LIVE_MAPPING_V2_12,
    League.TENNIS_WTA_LIVE_MAPPING_V2_13,
    League.TENNIS_WTA_LIVE_MAPPING_V2_14,
    League.TENNIS_WTA_LIVE_MAPPING_V2_15,
    League.TENNIS_WTA_LIVE_MAPPING_V2_16,
    League.TENNIS_WTA_LIVE_MAPPING_V2_17,
    League.TENNIS_WTA_LIVE_MAPPING_V2_18,
    League.TENNIS_WTA_LIVE_MAPPING_V2_19,
    League.TENNIS_WTA_LIVE_MAPPING_V2_20,
    League.TENNIS_WTA_LIVE_MAPPING_V2_21,
    League.TENNIS_WTA_LIVE_MAPPING_V2_22,
    League.TENNIS_WTA_LIVE_MAPPING_V2_23,
];

export const LEAGUES_NO_LIVE_CONSTRAINTS = [League.SUMMER_OLYMPICS_RUGBY, League.SUMMER_OLYMPICS_RUGBY_WOMEN];

export const AMERICAN_LEAGUES = [
    League.NCAAF,
    League.NFL,
    League.MLB,
    League.NBA,
    League.NCAAB,
    League.NHL,
    League.WNBA,
    League.MLS,
    League.IPL,
    League.T20_BLAST,
];

export const UFC_LEAGUE_IDS = [701, 702, 703, 704];

export const LeagueIdMapRundown = {
    1: 1, // NCAAF
    2: 2, // NFL
    3: 3, // MLB
    4: 4, // NBA
    5: 5, // NCAAB
    6: 6, // NHL
    7: 7, // UFC
    8: 8, // WNBA
    10: 10, // MLS
    11: 11, // EPL
    12: 12, // France League 1
    13: 13, // Bundesliga
    14: 14, // La Liga
    15: 15, // Seria A
    16: 16, // Champions League
    17: 17, // Europa League
    18: 18, // FIFA WC
    19: 19, // J1
    20: 20, // IPL
    21: 21, // T20
};

export const LeagueIdMapEnetpulse = {
    320: 18, // Hockey Norway
    6: 24, // NHL
    33: 33, // Hockey World Championship
    16: 42, // Champions League
    44: 44, // Copa America
    45: 45, // Copa Libertadores
    11: 47, // EPL
    50: 50, // UEFA EURO
    12: 53, // France League 1
    13: 54, // Bundesliga
    15: 55, // Seria A
    57: 57, // Netherlands League 1
    61: 61, // Portugal League 1
    65: 65, // Summer Olympics Soccer Women
    66: 66, // Summer Olympics Soccer
    17: 73, // Europa League
    76: 76, // World Cup Woman
    14: 87, // La Liga
    152: 152, // Tennis WTA
    153: 153, // Tennis GS
    156: 156, // Tennis Masters 1000
    158: 158, // Summer Olympics Tennnis
    132: 132, // FA Cup
    134: 134, // Coupe de France
    138: 138, // Copa del Rey
    141: 141, // Coppa Italia
    209: 209, // DFB Pokal
    230: 230, // LIGA MX
    268: 268, // Brazil Football League
    288: 288, // EURO U21
    296: 296, // FIFA WC U20
    310: 310, // Hockey Czech
    319: 319, // Hockey Finland
    322: 322, // Hockey Germany
    327: 327, // Hockey Switzerland
    380: 380, // Summer Olympics Handball Women
    381: 381, // Summer Olympics Handball
    399: 399, // EuroLeague
    406: 406, // Summer Olympics Basketball
    407: 407, // Summer Olympics Basketball Women
    409: 409, // FIBA World Cup
    445: 445, // F1
    453: 453, // Summer Olympics Beach Voleyball Women
    454: 454, // Summer Olympics Beach Voleyball
    497: 497, // Moto GP
    536: 536, // Saudi Arabia Football League
    8881: 8881, // Summer Olympics Water Polo
    8893: 8893, // Summer Olympics Voleyball Women
    8894: 8894, // Summer Olympics Voleyball
    8910: 8910, // Summer Olympics Table Tennnis
    9196: 9196, // Boxing
    9578: 9578, // Summer Olympics Rugby
    9588: 9588, // Summer Olympics Rugby Women
    9698: 9698, // Summer Olympics Hockey Women
    9699: 9699, // Summer Olympics Hockey
    9806: 9806, // UEFA League of Nations
    9821: 9821, // CONCACAF League of Nations
    9977: 9977, // CsGo
    9983: 9983, // Dota
    10071: 10071, // Summer Olympics Basketball 3x3
    10072: 10072, // Summer Olympics Basketball 3x3 Women
    10502: 10502, // Summer Olympics Basketball Qualification
    10138: 10138, // LOL
    10199: 10199, // World Cup Qualifications CONMBOL
    10216: 10216, // Europa Conference League
    10595: 10595, // Non-Title Boxing
    10611: 10611, // Champions League Qualification
    10613: 10613, // Europa League Qualification
    10615: 10615, // Conference League Qualification
};

export const LeagueIdMapOpticOdds = {
    1: 'NCAAF',
    2: 'NFL',
    3: 'MLB',
    4: 'NBA',
    5: 'NCAAB',
    6: 'NHL',
    7: 'UFC',
    8: 'WNBA',
    10: 'USA - Major League Soccer',
    11: 'England - Premier League',
    12: 'France - Ligue 1',
    13: 'Germany - Bundesliga',
    14: 'Spain - La Liga',
    15: 'Italy - Serie A',
    16: 'UEFA - Champions League',
    17: 'UEFA - Europa League',
    18: 'FIFA - World Cup Qualifiers',
    19: 'Japan - J1 League',
    45: 'CONMEBOL - Copa Libertadores',
    57: 'Netherlands - Eredivisie',
    61: 'Portugal - Primeira Liga',
    132: 'England - FA Cup',
    134: 'France - Coupe de France',
    138: 'Spain - Copa del Rey',
    152: 'WTA',
    156: 'ATP',
    141: 'Italy - Coppa Italia',
    209: 'Germany - DFB Pokal',
    230: 'Mexico - Liga MX',
    268: 'Brazil - Serie A',
    310: 'Czech Republic - Extraliga',
    319: 'Finland - SM Liiga',
    321: 'Russia - KHL',
    322: 'Germany - DEL',
    323: 'Austria - Ice Hockey League',
    324: 'Sweden - SHL',
    327: 'Switzerland - National League',
    399: 'Euroleague',
    536: 'Saudi Arabia - Saudi League',
    9806: 'UEFA - Nations League',
    9977: 'CS2',
    9983: 'Dota 2',
    10138: 'League of Legends',
    10216: 'UEFA - Europa Conference League',
    20001: 'UEFA - Super Cup',
    20002: 'Brazil - Copa do Brasil',
    20011: 'England - Championship',
    20101: 'Scotland - Premiership',
    20102: 'Belgium - Jupiler Pro League',
    20103: 'Czech Republic - FNL',
    20104: 'Chile - Primera Division',
    20105: 'Finland - Veikkausliiga',
    20106: 'Argentina - Primera Division',
    20107: 'Russia - Premier League',
    20108: 'Turkey - Super Lig',
    20109: 'Serbia - Super Liga',
    20110: 'Greece - Super League',
    20111: 'India - Calcutta Premier Division',
    20112: 'China - Super League',
    20113: 'Australia - A-League',
    20114: 'Switzerland - Super League',
    20115: 'Germany - Bundesliga 2',
    20116: 'Spain - La Liga 2',
    20117: 'Italy - Serie B',
    20118: 'India - Super League',
    20119: 'France - Ligue 2',
    20120: 'Austria - Bundesliga',
    20121: 'Denmark - Superliga',
    20122: 'Poland - Ekstraklasa',
    20123: 'Sweden - Allsvenskan',
    20124: 'Colombia - Primera A',
    20125: 'England - EFL Cup',
    20126: 'England - League 1',
    20127: 'Uruguay - Primera Division',
    20128: 'AFC - Champions League',
    20129: 'Italy - Supercoppa',
    20130: 'France - Super Cup',
    20131: 'Spain - Supercopa',
    20132: 'Germany - Super Cup',
    20133: 'Portugal - League Cup',
    20134: 'Thailand - Thai League 1',
    20135: 'Netherlands - KNVB Beker',
    20136: 'Portugal - Taca de Portugal',
    20137: 'England - Womens Super League',
    20138: 'Italy - Serie A Femminile',
    20139: 'France - Premiere Ligue',
    20140: 'Germany - Frauen Bundesliga',
    20141: 'Spain - Liga F',
    20142: 'Netherlands - Vrouwen Eredivisie',
    20143: 'Belgium - Womens Super League',
    20144: 'UEFA - Champions League Women',
    20145: 'USA - NWSL',
    20146: 'Australia - A-League Women',
    20147: 'CONCACAF - Champions Cup',
    20200: 'Eurocup',
    20201: 'Spain - Liga ACB',
    20202: 'Italy - Lega Basket Serie A',
    20203: 'Germany - BBL',
    20204: 'France - LNB Pro A',
    20205: 'China - CBA',
    20206: 'Australia - NBL',
    20211: 'NCAAW',
    20212: 'FIBA - Americup Qualifiers',
    20213: 'FIBA - Asia Cup Qualifiers',
    20214: 'FIBA - Eurobasket Qualifiers',
    20215: 'FIBA - World Cup Qualifiers',
    20297: 'Rocket League',
    20298: 'Call of Duty',
    20299: 'Starcraft',
    20300: 'Valorant',
};
